name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipycanvas
  - matplotlib
  - seaborn
  - plotnine
  - pandas
  - statsmodels
  - scikit-learn
  - scipy
  - sqlite
  - altair
  - ipympl
  - ipyleaflet
  - ipydatagrid
  - ipycanvas
  - vega_datasets
  - plotly
  - black
  - xarray
  - httpx
  - scikit-image
